# Generated by Django 4.2.13 on 2024-05-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={"ordering": ("-date_created",)},
        ),
    ]
